
/*******************************************
 **** Generated by Respack Version 0.0.1 ****
 *******************************************/
public class ResPack0 {

	public final static int STRINGS_PACK = 0;
	public final static int IMAGE_PACK = 1;
	public final static int IMAGE1_4x4 = 2;
	public final static int IMAGE1_8x8 = 3;
	public final static int IMAGE1_10x10 = 4;
	public final static int IMAGE1_12x12 = 5;
	public final static int IMAGE1_16x16 = 6;
	public final static int IMAGE1_20x20 = 7;
	public final static int IMAGE1_32x32 = 8;
	public final static int IMAGE1_48x48 = 9;
	public final static int IMAGE1_64x64 = 10;
	public final static int IMAGE2_4x4 = 11;
	public final static int IMAGE2_8x8 = 12;
	public final static int IMAGE2_10x10 = 13;
	public final static int IMAGE2_12x12 = 14;
	public final static int IMAGE2_16x16 = 15;
	public final static int IMAGE2_20x20 = 16;
	public final static int IMAGE2_32x32 = 17;
	public final static int IMAGE2_48x48 = 18;
	public final static int IMAGE2_64x64 = 19;
}
